---
title: "<span style='font-size: 90px;'>模块九 DeepSeek辅助傻瓜式医学统计</span>"
date: today
author: "李宗璋"
format: 
  revealjs:
    incremental: FALSE
    theme: sky
    slide-number: true
    chalkboard: 
      buttons: false
    preview-links: auto
    css: styles.css
    footer: <https://lizongzhang.github.io/deepseekcamp>
    include-before-body: header.html
---

## Chapter 1 Overview of Statistical Analysis and Excel {auto-animate="true"}

-   1.1 Steps of Statistical Analysis  
-   1.2 Statistical Analysis Tools in Excel  
-   1.3 Common Excel Techniques  
-   1.4 Data Cleaning Tools in Excel

## 1.1 Steps of Statistical Analysis

::: incremental
-   1.1.1 Data Collection  
-   1.1.2 Data Organization  
-   1.1.3 Data Analysis  
-   1.1.4 Conclusion Extraction  
:::

## 1.1.1 Data Collection

::: nonincremental
-   Macroeconomic data  
-   Microeconomic data  
-   Cross-sectional data  
-   Time series data  
-   Qualitative data  
-   Quantitative data  
:::

## 1.1.2 Data Organization

-   Convert data into structured tables, where each row represents an observation unit and each column represents a variable.  
-   Check data completeness and validity, including identifying duplicates, missing values, and outliers, and converting text into numerical codes.  
-   See: 1.4 Data Cleaning Tools in Excel  

## 1.1.3 Data Analysis

-   Descriptive statistics: Present data using tables and charts; compute descriptive measures such as mean, median, and standard deviation.  
-   Inferential statistics: Draw inferences about the population based on sample data.  

## 1.1


